### The ra/dec coordinates from the Bersier & Wood dataset sometimes were less accurate than the coordinates in their names
### This notebook aims to solve that problem by replacing the ra/dec values with the values in each object's name

In [2]:
#Imports
from astroquery.gaia import Gaia
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
import astropy.units as units
import csv
import pandas as pd
from lsst.rsp import get_tap_service

from sklearn import svm

In [3]:
Vizier.ROW_LIMIT = -1

In [4]:
catalog_list = Vizier.get_catalogs('J/AJ/123/840')

In [5]:
print(catalog_list.keys())

['J/AJ/123/840/table1', 'J/AJ/123/840/table2', 'J/AJ/123/840/table3', 'J/AJ/123/840/table4']

**Table 1 contains information about the rest of the tables**

**Table 2, 3, and 4 are rrl, ceph, lpv**

In [6]:
bw_table_rrl = catalog_list[1]
bw_table_ceph = catalog_list[2]
bw_table_lpv = catalog_list[3]

In [7]:
bw_df_rrl = bw_table_rrl.to_pandas()
bw_df_ceph = bw_table_ceph.to_pandas()
bw_df_lpv = bw_table_lpv.to_pandas()

**Adding labels so that objects can be identified after merging tables**

In [8]:
bw_df_rrl['Main Class'] = 'RR Lyrae'
bw_df_ceph['Main Class'] = 'Cepheid'
bw_df_lpv['Main Class'] = 'Long Period Variable'

In [9]:
bw_df_all = pd.concat([bw_df_rrl, bw_df_ceph, bw_df_lpv], axis=0, ignore_index=False)

In [10]:
bw_df_all

,FBW,o_Vmag,Vmag,e_Vmag,o_Icmag,Icmag,e_Icmag,WS,Period,E(B-V),_RA,_DE,Main Class,V-Ic,e_V-Ic,Per,Class,o_V-Ic,OName,n_FBW
0,J023926.4-344027,28.0,21.320999,0.028,27.0,20.799000,0.042,1.030,0.37206,0.025,39.8600,-34.6742,RR Lyrae,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,J023749.8-342427,24.0,21.389000,0.027,24.0,20.754999,0.036,1.422,0.54365,0.028,39.4575,-34.4075,RR Lyrae,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,J023750.8-342736,32.0,21.346001,0.021,31.0,20.743999,0.035,2.741,0.58252,0.030,39.4617,-34.4600,RR Lyrae,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,J023751.9-342620,32.0,21.419001,0.023,32.0,20.886999,0.033,1.139,0.58052,0.029,39.4662,-34.4389,RR Lyrae,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,J023752.8-344615,32.0,21.469000,0.029,32.0,20.559999,0.033,2.005,0.16459,0.034,39.4700,-34.7708,RR Lyrae,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,J024048.3-343536,14.0,17.375000,0.013,NaN,NaN,NaN,NaN,NaN,0.023,40.2012,-34.5933,Long Period Variable,1.922,0.021,NaN,NaN,11.0,S144,?
81,J024052.2-343723,15.0,18.370001,0.015,NaN,NaN,NaN,NaN,NaN,0.023,40.2175,-34.6231,Long Period Variable,2.100,0.025,NaN,NaN,14.0,DK23,?
82,J024103.5-344805,33.0,20.412001,0.097,NaN,NaN,NaN,NaN,NaN,0.024,40.2646,-34.8014,Long Period Variable,3.793,0.101,NaN,NaN,34.0,,
83,J024110.8-343151,14.0,18.513000,0.015,NaN,NaN,NaN,NaN,NaN,0.022,40.2950,-34.5308,Long Period Variable,2.107,0.025,NaN,NaN,13.0,"S153, DI16",
84,J024111.5-345504,29.0,18.392000,0.018,NaN,NaN,NaN,NaN,NaN,0.025,40.2979,-34.9178,Long Period Variable,2.280,0.023,NaN,NaN,30.0,,

In [11]:
bw_df_all['Class'].unique()

array([nan, 'P2C', 'AC', 'blue', 'P2C?'], dtype=object)

**New subset with only FBW (name), _RA, and _DE (coordinates)**

In [12]:
bw_df_all_subset = bw_df_all[['FBW', '_RA', '_DE']]

**Making another subsetwith only name**

In [13]:
bw_df_names = bw_df_all_subset['FBW']

In [15]:
bw_df_names

0     J023926.4-344027
1     J023749.8-342427
2     J023750.8-342736
3     J023751.9-342620
4     J023752.8-344615
            ...
80    J024048.3-343536
81    J024052.2-343723
82    J024103.5-344805
83    J024110.8-343151
84    J024111.5-345504
Name: FBW, Length: 624, dtype: object

**Converting names to coordinates**

In [17]:
bw_df_coords = SkyCoord(bw_df_names.tolist(), unit=(units.hourangle, units.deg), frame='icrs')

In [18]:
bw_df_ra = bw_df_coords.ra.deg
bw_df_dec = bw_df_coords.dec.deg

In [19]:
bw_df_ra

array([39.86      , 39.4575    , 39.46166667, 39.46625   , 39.47      ,
       39.4725    , 39.47916667, 39.48333333, 39.48375   , 39.48583333,
       39.4875    , 39.4875    , 39.49      , 39.49375   , 39.495     ,
       39.49625   , 39.49833333, 39.49833333, 39.50041667, 39.50041667,
       39.50125   , 39.50166667, 39.50458333, 39.50583333, 39.50666667,
       39.50875   , 39.51166667, 39.51791667, 39.51916667, 39.51958333,
       39.52708333, 39.52708333, 39.52875   , 39.53      , 39.53      ,
       39.53458333, 39.53666667, 39.54208333, 39.54458333, 39.54583333,
       39.55375   , 39.55375   , 39.55625   , 39.56791667, 39.57      ,
       39.575     , 39.57625   , 39.58125   , 39.58166667, 39.58291667,
       39.58291667, 39.58583333, 39.59      , 39.59041667, 39.5925    ,
       39.59916667, 39.6025    , 39.60625   , 39.61125   , 39.6125    ,
       39.61458333, 39.61666667, 39.61666667, 39.61916667, 39.61916667,
       39.62      , 39.62291667, 39.625     , 39.62541667, 39.63041667,
       39.63166667, 39.63291667, 39.63375   , 39.635     , 39.63541667,
       39.6375    , 39.64166667, 39.64208333, 39.64208333, 39.64291667,
       39.64625   , 39.64666667, 39.64791667, 39.65      , 39.65083333,
       39.65333333, 39.65416667, 39.65458333, 39.65791667, 39.65833333,
       39.66041667, 39.66625   , 39.66916667, 39.67      , 39.67041667,
       39.67041667, 39.67416667, 39.67666667, 39.67666667, 39.68416667,
       39.68416667, 39.68666667, 39.68791667, 39.68833333, 39.69      ,
       39.69083333, 39.69083333, 39.69166667, 39.69333333, 39.69416667,
       39.69416667, 39.69541667, 39.69541667, 39.70541667, 39.70583333,
       39.70625   , 39.70791667, 39.70916667, 39.71166667, 39.7125    ,
       39.71333333, 39.71625   , 39.71708333, 39.71791667, 39.71916667,
       39.71958333, 39.72333333, 39.72458333, 39.725     , 39.7275    ,
       39.72916667, 39.72958333, 39.73083333, 39.73416667, 39.735     ,
       39.74      , 39.7425    , 39.7425    , 39.7425    , 39.74583333,
       39.74583333, 39.74708333, 39.74833333, 39.75041667, 39.75083333,
       39.75125   , 39.75166667, 39.75208333, 39.76      , 39.76333333,
       39.76541667, 39.76708333, 39.7675    , 39.76916667, 39.77      ,
       39.77041667, 39.77083333, 39.77333333, 39.77458333, 39.77625   ,
       39.77791667, 39.77916667, 39.77958333, 39.78083333, 39.78125   ,
       39.78375   , 39.79208333, 39.79375   , 39.795     , 39.79541667,
       39.79583333, 39.79833333, 39.79833333, 39.79875   , 39.79916667,
       39.80041667, 39.80208333, 39.80458333, 39.80458333, 39.80625   ,
       39.80708333, 39.80791667, 39.81166667, 39.81458333, 39.81708333,
       39.8175    , 39.81791667, 39.81875   , 39.82083333, 39.82166667,
       39.82416667, 39.82583333, 39.82708333, 39.82791667, 39.83083333,
       39.8325    , 39.83291667, 39.83541667, 39.83625   , 39.83666667,
       39.84166667, 39.84375   , 39.845     , 39.84583333, 39.84708333,
       39.8475    , 39.84875   , 39.84958333, 39.85125   , 39.8525    ,
       39.85333333, 39.85416667, 39.85708333, 39.85791667, 39.86083333,
       39.86291667, 39.86291667, 39.86333333, 39.86375   , 39.865     ,
       39.86708333, 39.87291667, 39.8975    , 39.89958333, 39.90083333,
       39.9025    , 39.91291667, 39.91625   , 39.91666667, 39.91958333,
       39.91958333, 39.92541667, 39.93208333, 39.9325    , 39.93291667,
       39.93625   , 39.93833333, 39.93916667, 39.94166667, 39.94333333,
       39.94708333, 39.94791667, 39.94958333, 39.95041667, 39.95458333,
       39.95541667, 39.95916667, 39.96708333, 39.9675    , 39.97166667,
       39.97583333, 39.97833333, 39.97958333, 39.98416667, 39.98625   ,
       39.98708333, 39.9875    , 39.98916667, 39.98958333, 39.98958333,
       39.99041667, 39.99041667, 39.99125   , 39.99375   , 39.99666667,
       39.99875   , 40.00083333, 40.00083333, 40.00291667, 40.00375   ,
       40.00541667, 40.01      , 40.01208333, 40.01333333, 40.015     ,
       40.01625   , 40.01916667, 40.02208333, 40.02583333, 40.02708333,
       40.02875   , 40.03333333, 40.04041667, 40.04666667, 40.04791667,
       40.05208333, 40.05291667, 40.05416667, 40.05666667, 40.05666667,
       40.05708333, 40.06125   , 40.06458333, 40.06625   , 40.07666667,
       40.07708333, 40.07791667, 40.08      , 40.08166667, 40.08166667,
       40.08333333, 40.08458333, 40.08625   , 40.08708333, 40.08958333,
       40.09583333, 40.09583333, 40.09875   , 40.1       , 40.11166667,
       40.11708333, 40.12541667, 40.12541667, 40.12791667, 40.13583333,
       40.13708333, 40.13791667, 40.14166667, 40.15      , 40.15166667,
       40.1525    , 40.16458333, 40.16541667, 40.16666667, 40.16708333,
       40.17416667, 40.18166667, 40.18208333, 40.1875    , 40.19291667,
       40.19375   , 40.19625   , 40.19708333, 40.19875   , 40.20083333,
       40.20541667, 40.20666667, 40.21      , 40.21458333, 40.21458333,
       40.21875   , 40.22875   , 40.23      , 40.23166667, 40.23291667,
       40.24291667, 40.24416667, 40.24625   , 40.2525    , 40.25541667,
       40.25666667, 40.26291667, 40.27708333, 39.8175    , 39.91166667,
       39.91375   , 39.9175    , 39.9175    , 39.91916667, 39.91916667,
       39.92125   , 39.92125   , 39.9225    , 39.9225    , 39.92541667,
       39.93041667, 39.93583333, 39.94041667, 39.94041667, 39.9425    ,
       39.94416667, 39.94625   , 39.95208333, 39.95666667, 39.95666667,
       39.95958333, 39.96375   , 39.96375   , 39.97791667, 39.97916667,
       39.98041667, 39.98083333, 39.98375   , 39.98625   , 39.98708333,
       39.98833333, 39.9925    , 39.99375   , 39.99625   , 39.99666667,
       39.99833333, 39.99833333, 39.99958333, 40.00666667, 40.0075    ,
       40.00958333, 40.01083333, 40.0125    , 40.01416667, 40.01875   ,
       40.01875   , 40.01958333, 40.02083333, 40.02166667, 40.02833333,
       40.0425    , 40.04791667, 40.04833333, 40.04916667, 40.05166667,
       40.05333333, 40.05625   , 40.05666667, 40.05708333, 40.06125   ,
       40.06208333, 40.0625    , 40.065     , 40.06583333, 40.06625   ,
       40.06666667, 40.0675    , 40.06916667, 40.06916667, 40.0725    ,
       40.07333333, 40.07958333, 40.08041667, 40.08166667, 40.08166667,
       40.08708333, 40.0875    , 40.09      , 40.09291667, 40.09708333,
       40.09791667, 40.10125   , 40.10291667, 40.10458333, 40.10583333,
       40.10625   , 40.10958333, 40.115     , 40.11916667, 40.12      ,
       40.12291667, 40.12291667, 40.13208333, 40.13541667, 40.13625   ,
       40.13833333, 40.13875   , 40.13958333, 40.14041667, 40.14125   ,
       40.14291667, 40.14625   , 40.14708333, 40.14875   , 40.15458333,
       40.15541667, 40.15833333, 40.15875   , 40.1625    , 40.16291667,
       40.16666667, 40.16666667, 40.17125   , 40.17125   , 40.17291667,
       40.17541667, 40.18166667, 40.18333333, 40.18583333, 40.18875   ,
       40.19125   , 40.19208333, 40.19708333, 40.19875   , 40.20166667,
       40.20375   , 40.20541667, 40.20708333, 40.20958333, 40.21166667,
       40.21458333, 40.21541667, 40.21708333, 40.2175    , 40.22208333,
       40.22208333, 40.22291667, 40.22291667, 40.22541667, 40.2275    ,
       40.23666667, 40.23708333, 40.24333333, 40.24625   , 40.25166667,
       40.255     , 40.25875   , 40.26208333, 40.26333333, 40.26458333,
       40.2675    , 40.26833333, 40.26875   , 40.27      , 40.27458333,
       40.28583333, 40.28666667, 40.2875    , 40.2975    , 40.30625   ,
       39.51625   , 39.54958333, 39.67916667, 39.71833333, 39.7225    ,
       39.77958333, 39.86208333, 39.86166667, 39.8625    , 39.90708333,
       39.92291667, 39.93833333, 39.9425    , 39.96875   , 39.97291667,
       39.97833333, 40.00375   , 40.01125   , 40.0425    , 40.07041667,
       40.0725    , 40.095     , 40.20916667, 40.24291667, 39.5       ,
       39.52541667, 39.5525    , 39.57125   , 39.58875   , 39.59166667,
       39.59416667, 39.60958333, 39.62583333, 39.63916667, 39.66708333,
       39.67541667, 39.68541667, 39.71458333, 39.72083333, 39.73083333,
       39.73708333, 39.7375    , 39.7425    , 39.77291667, 39.79458333,
       39.79666667, 39.79958333, 39.80166667, 39.81958333, 39.82416667,
       39.83875   , 39.845     , 39.84708333, 39.85041667, 39.85041667,
       39.85541667, 39.85708333, 39.86083333, 39.87166667, 39.87416667,
       39.90833333, 39.915     , 39.92      , 39.9225    , 39.9325    ,
       39.93333333, 39.93791667, 39.95458333, 39.96416667, 39.96583333,
       39.97166667, 39.9775    , 39.99416667, 40.00375   , 40.00541667,
       40.01041667, 40.01125   , 40.01083333, 40.02208333, 40.02291667,
       40.02541667, 40.02666667, 40.03375   , 40.03416667, 40.0375    ,
       40.04208333, 40.04583333, 40.04875   , 40.05083333, 40.05875   ,
       40.065     , 40.07125   , 40.07375   , 40.07916667, 40.08041667,
       40.08291667, 40.09416667, 40.10416667, 40.13      , 40.13291667,
       40.16291667, 40.16333333, 40.16583333, 40.19125   , 40.20125   ,
       40.2175    , 40.26458333, 40.295     , 40.29791667])

In [20]:
bw_df_all_subset.loc[:, 'New RA'] = bw_df_ra
bw_df_all_subset.loc[:, 'New DEC'] = bw_df_dec

/tmp/ipykernel_17617/2021585380.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bw_df_all_subset.loc[:, 'New RA'] = bw_df_ra
/tmp/ipykernel_17617/2021585380.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bw_df_all_subset.loc[:, 'New DEC'] = bw_df_dec

In [21]:
bw_df_all_subset

                 FBW      _RA      _DE     New RA    New DEC
0   J023926.4-344027  39.8600 -34.6742  39.860000 -34.674167
1   J023749.8-342427  39.4575 -34.4075  39.457500 -34.407500
2   J023750.8-342736  39.4617 -34.4600  39.461667 -34.460000
3   J023751.9-342620  39.4662 -34.4389  39.466250 -34.438889
4   J023752.8-344615  39.4700 -34.7708  39.470000 -34.770833
..               ...      ...      ...        ...        ...
80  J024048.3-343536  40.2012 -34.5933  40.201250 -34.593333
81  J024052.2-343723  40.2175 -34.6231  40.217500 -34.623056
82  J024103.5-344805  40.2646 -34.8014  40.264583 -34.801389
83  J024110.8-343151  40.2950 -34.5308  40.295000 -34.530833
84  J024111.5-345504  40.2979 -34.9178  40.297917 -34.917778

[624 rows x 5 columns]

In [22]:
path = os.getcwd()
vstars_path = os.path.join(path, 'v_stars.csv')
vstars_path

'/home/jakedlr/notebooks/tutorials/v_stars.csv'

In [23]:
v_stars_df = pd.read_csv(vstars_path)

In [24]:
v_stars_df

,ra,dec,period,Vmag,e_Vmag,Icmag,e_Icmag,E(B-V),source,main category,...,iamp,e_iamp,vamp_sec,e_vamp_sec,bamp_sec,e_bamp_sec,gmag,bpmag,rpmag,bp-rp
0,39.860000,-34.674200,0.372060,21.321,0.028,20.799,0.042,0.025,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.457500,-34.407500,0.543650,21.389,0.027,20.755,0.036,0.028,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,39.461700,-34.460000,0.582520,21.346,0.021,20.744,0.035,0.030,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39.466200,-34.438900,0.580520,21.419,0.023,20.887,0.033,0.029,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39.470000,-34.770800,0.164590,21.469,0.029,20.560,0.033,0.034,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,40.441648,-34.291025,NaN,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.425013,18.622169,16.353251,2.268919
895,40.222196,-34.203659,243.829816,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.899149,18.981697,16.645916,2.335781
896,39.742913,-34.536605,203.290829,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.573246,18.800655,16.482256,2.318399
897,39.919195,-34.337461,163.279808,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,16.944231,18.394299,15.806978,2.587320
898,40.642356,-33.766035,541.661598,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,9.194800,11.784486,7.745113,4.039372

**Setting ra and dec in v_stars_df to the newly calculated ra/dec**

In [25]:
v_stars_df.loc[v_stars_df['source'] == 'Bersier Wood', 'ra'] = bw_df_ra
v_stars_df.loc[v_stars_df['source'] == 'Bersier Wood', 'dec'] = bw_df_dec

In [29]:
v_stars_df

,ra,dec,period,Vmag,e_Vmag,Icmag,e_Icmag,E(B-V),source,main category,...,iamp,e_iamp,vamp_sec,e_vamp_sec,bamp_sec,e_bamp_sec,gmag,bpmag,rpmag,bp-rp
0,39.860000,-34.674167,0.372060,21.321,0.028,20.799,0.042,0.025,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.457500,-34.407500,0.543650,21.389,0.027,20.755,0.036,0.028,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,39.461667,-34.460000,0.582520,21.346,0.021,20.744,0.035,0.030,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,39.466250,-34.438889,0.580520,21.419,0.023,20.887,0.033,0.029,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,39.470000,-34.770833,0.164590,21.469,0.029,20.560,0.033,0.034,Bersier Wood,RRLyrae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,40.441648,-34.291025,NaN,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.425013,18.622169,16.353251,2.268919
895,40.222196,-34.203659,243.829816,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.899149,18.981697,16.645916,2.335781
896,39.742913,-34.536605,203.290829,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,17.573246,18.800655,16.482256,2.318399
897,39.919195,-34.337461,163.279808,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,16.944231,18.394299,15.806978,2.587320
898,40.642356,-33.766035,541.661598,NaN,NaN,NaN,NaN,NaN,Gaia,LPV,...,NaN,NaN,NaN,NaN,NaN,NaN,9.194800,11.784486,7.745113,4.039372

**Move to csv**

In [72]:
v_stars_df.to_csv('v_stars_updated.csv', index=False)